# -*- coding: utf-8 -*-
"""Step 0 - Converting to CSV files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SX84YlHlXeAs-DeoQ-PEcLIg9Dce1Qfc

We use this notebook to convert the the Excel files of the datasources CSVs as these are much faster to load and save compared to Excels.
"""

import pandas as pd
import os

input_folder = "Cleaned Data - Excel/"
output_folder = "Cleaned Data/"

datasources = [x.replace(".xlsx", "") for x in os.listdir(input_folder)]
datasources

for datasource in datasources:
# for datasource in ['IJ_Global', "REFINITIV_LOAN"]:
    print(datasource)
    db = pd.read_excel(input_folder + datasource + ".xlsx")
    db.to_csv(output_folder + datasource + ".csv", index=False)

tmp = pd.read_csv("Cleaned Data/BU_CGP.csv")

tmp.loc[tmp['location_id'] == 1114791]

